### PR TITLE
Added Promises to async read/write operations

### PR DESCRIPTION
**Pull request by saenglert**
This PR addresses #127

### CODE REVIEW

**Comment by fivdi** [comment]
@saenglert Thank you for this pull request.

I haven't tested this PR but the code modifications look good to me. What I do see as an issue is the lack of integration tests and unit tests.

Here's a summary of the code coverage form the [last master build](https://travis-ci.com/fivdi/onoff/jobs/180034485):
```
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |    96.49 |    94.87 |      100 |     99.1 |                   |
 onoff.js |    96.49 |    94.87 |      100 |     99.1 |               110 |
----------|----------|----------|----------|----------|-------------------|
```
And here's a summary of the code coverage form this [PRs build](https://travis-ci.com/fivdi/onoff/jobs/180059549):
```
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |     93.7 |    87.78 |      100 |    95.97 |                   |
 onoff.js |     93.7 |    87.78 |      100 |    95.97 |... 78,179,181,202 |
----------|----------|----------|----------|----------|-------------------|
```
As can be seen, the numbers are down by up to 7% which is a lot.

Additional work related to integration tests and unit tests would be needed before this PR can be merged.

**Comment by saenglert** [comment]
@fivdi Working on it

**Comment by saenglert** [comment]
Ok, according to the testing suite I've added tests for all functions I added.

I took the liberty to create a `util` folder in `test` and add my own async equals function. This should probably be sooner or later be replaced by an actuall async testing framework.

Mocha mentions [chai-as-promised](https://www.npmjs.com/package/chai-as-promised) in their docu.

While typing I just noticed the Travis CI failing on it's Node 6 tests: While it wouldn't be much of a hassel to write the test purely Promise based, Node 6 LTS has I believe 2 months of support left so I leave the decision up to you how to procede.

**Comment by fivdi** [comment]
Thank you for working on this.

The `util` folder isn't an issue.

> While typing I just noticed the Travis CI failing on its Node 6 tests: While it wouldn't be much of a hassel to write the test purely Promise based, Node 6 LTS has I believe 2 months of support left so I leave the decision up to you how to procede.

Yes, two month and a few days according to the [release schedule](https://github.com/nodejs/Release). Today, onoff still supports Node 6 and I'd prefer if the unit tests also supported Node 6. This in turn means that I'd prefer purely Promise base code.

**Comment by fivdi** [comment]
Coverage is good now:
```
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |    96.83 |    94.32 |      100 |    99.19 |                   |
 onoff.js |    96.83 |    94.32 |      100 |    99.19 |               110 |
----------|----------|----------|----------|----------|-------------------|
```
Initial tests on a Pi 3 with Node 10 look good. I'll merge and publish on npm as soon as possible.

**Comment by fivdi** [comment]
Officially this is a breaking change because the return values from `read` and `write` is now a `Promise` rather than `undefined` if no completion callback is specified.

**Comment by mbrevda** [comment]
Thanks!

**Pull request merged**
