### PR TITLE
guard for non HIGH LOW values

### PR DESCRIPTION
**Pull request by johntalton**
- not sure if you want to throw Error or something else.
- not sure about timing of next_tick for callback (but it looks like this is correct per rest of code)
- someone please change my error messages :)
- are there other location that should have similar restrictions?
- should it be moved to a validator function (aka i2cbus `checkHighLow`)?
- README updates?

reference #104

### CODE REVIEW

**Comment by fivdi** [comment]
@johntalton Give me some time to  think about this...

**Comment by johntalton** [comment]
alternatively !Number.isNaN + range check could be used.  My understanding is that the sysfs interfaces "supports" analog pins; and writing 0-255 is valid. 

That however goes against this libraries binary naming :)

**Comment by fivdi** [comment]
> My understanding is that the sysfs interfaces "supports" analog pins; and writing 0-255 is valid.

According to the documentation any non-zero value is treated as a HIGH (see description of "value" at https://www.kernel.org/doc/Documentation/gpio/sysfs.txt). Maybe the documentation isn't up to date. I'm not sure. LEDs can also be controlled with sysfs files and there's a sysfs file called brightness that supports values other than 0 and 1 (https://www.kernel.org/doc/Documentation/leds/leds-class.txt)

> That however goes against this libraries binary naming :)

Thers's a grey zone bethween on and off :)

**Comment by fivdi** [comment]
@johntalton After thinking about this I've decided to leave things as they are. The documentation for [write](https://github.com/fivdi/onoff#writevalue-callback) and [writeSync](https://github.com/fivdi/onoff#writesyncvalue) state that the value passed should be 0 or 1. I'm not sure if there are people relying the side-effects of passing other undocumented values to the write and writeSync methods. Modifying the behaviour here would be a breaking change so I'll leave things as they are.

**Pull request closed without merging**
