### PR TITLE
Include workaround for the `node-gyp` issue

### PR DESCRIPTION
**Pull request by rakhbari**

### CODE REVIEW

**Comment by fivdi** [comment]
@rakhbari Thank you for the suggestion. However, recommending that people use the --unsafe-perm option isn't something that I would feel comfortable with as it allows scripts to be installed/run as root. The issue here isn't actually a node-gyp issue, it's a permission issue. The user attempting to install onoff doesn't have permission to install onoff in the directory where they would like to install it. The better solution is to ensure that the user wishing to perform the install has permission to install onoff in the directory they would like to install it in.

**Comment by rakhbari** [comment]
@fivdi Ok, fair enough. I'm also not one to want to go around proper permission issues, but I am one that likes to provide instructions for users that actually work with the current state of dependencies, or at least provide ways of making it work. As it stands, the current instructions in the `README` don't result in a working system.

Perhaps I didn't word the "workaround" with the proper warnings such as `this is circumventing permissions` or some such thing, but I really think you should consider providing something that allows the user to get their `onoff` installation working with the current state of dependencies, namely the issue with `npm`, when run as `root`, dropping privileges when executing `node-gyp`. How would you suggest a user attempting to install `onoff` solve this, without using `--unsafe-perm`? I'm all ears.

**Comment by fivdi** [comment]
> As it stands, the current instructions in the README don't result in a working system.

I don't believe this to be the case.

Calling `npm install onoff` works fine for me.

Unfortunately no information has been provided on how to reproduce the error. Assuming a Raspberry Pi is being used and Node.js has being successfully installed it should be possible to logon as user pi and execute the following commands to install onoff:

```
mkdir myapp
cd myapp
npm install onoff
```

If this doesn`t work please describe how to reproduce the error.

**Comment by rakhbari** [comment]
Sorry, should've provided my exact install cmd line:

    sudo nmp install -g onoff

Attempting to install the module in `global` mode using `sudo` as I need to be able to run nodejs and `onoff` at raspberry pi startup time with no user login (as root). Nodejs itself is installed globally under `/usr/local/`.

**Comment by fivdi** [comment]
If it's really necessary to install onoff globally (which is something I wouldn't recommend either) then npm have a good video describing how to fix npm permission issues at https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by rakhbari** [comment]
Ok @fivdi. Thanks for that link. I'll explore other avenues of resolving this. Sorry for the distractions.

**Comment by fivdi** [comment]
@rakhbari no problem.

**Comment by rakhbari** [comment]
Can you at the very least include a blurb about `if you attempt install with -g (globally) you'll get this error` and here's where you need to go to fix your permission issues? I'm a developer who's a developer and novice advocate and like really clear documentation for my stuff at least.

**Comment by fivdi** [comment]
To be honest the [Installation Section](https://github.com/fivdi/onoff/tree/v1.1.5#installation) of the README is already too long and explains too many exceptions. It would be better if it was shorter than it currently is rather than longer.

The EACCES error being discussed here isn't in any way related to onoff. The error will occur if an attempt is made to install any package globally with npm. The first time someone attempts to install any package globally they will see this error. Explaining this error in the onoff readme doesn't seem reasonable to me and it's not something that I want to do.

**Pull request closed without merging**
