### PR TITLE
Use Mocha and mocks to allow for testing without hardware.

### PR DESCRIPTION
**Pull request by thisboyiscrazy**
I needed this because i was doing development on a pc for a beaglebone

### CODE REVIEW

**Comment by fivdi** [comment]
Thank's for the PR :). I'll take a look at it after upgrading a few native add-ons to nan v2.3.2 for Node.js v6 compatibility.

**Comment by thisboyiscrazy** [comment]
Using v6 also causes issues with my test. mock-fs does not work if v6. But I was thinking can that be mock by using a real directory in the test/ i.e.

test/fs/export
test/fs/gpio7/{value,edge,direction}

then epoll would not have to be mocked. I think I can use rewrite to change GPIO_ROOT_PATH, might work.

**Comment by thisboyiscrazy** [comment]
I removed the need for mock-fs. but Epoll seems to still need to be mocked. Epoll does not work on regular files.

**Comment by fivdi** [comment]
@thisboyiscrazy I feel bad about closing this pull request. I'm sorry for not investing more time in the work you did here.

**Pull request closed without merging**
